version: "3"

services:
  postgres:
    container_name: postgres_suflex
    restart: unless-stopped
    image: postgres
    networks:
      - my-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: suflex
    ports:
      - 5432:5432
  app:
    stdin_open: true
    build: .
    container_name: app_suflex
    restart: always
    command: sh -c "yarn prisma:dev && yarn prisma:seed && yarn start:dev"
    networks:
      - my-network
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=stg
      - PORT=3333      
      - DATABASE_URL=postgresql://postgres:docker@postgres_suflex:5432/suflex?schema=suflex
    links:
      - postgres
    depends_on:
      - postgres

networks:
  my-network:
    driver: bridge